Project_3/src/objects/Diagnosis__c.object
<CustomObject>
    <label>Diagnosis</label>
    <nameField>
        <label>Diagnosis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnosis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project_3/src/objects/Diagnosis_Search_Junc__c.object
<CustomObject>
    <fields>
        <fullName>Chosen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chosen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Diagnosis__c</fullName>
        <label>Diagnosis</label>
        <referenceTo>Diagnosis__c</referenceTo>
        <relationshipLabel>Diagnosis-Search-Juncs</relationshipLabel>
        <relationshipName>Diagnosis_Search_Juncs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Likelihood__c</fullName>
        <label>Likelihood</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Diagnosis-Search-Junc</label>
    <nameField>
        <displayFormat>DSJ-{0}</displayFormat>
        <label>Diagnosis-Search-Junc Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diagnosis-Search-Juncs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project_3/src/classes/DiagnosisDiagnosisApexController.cls
public class DiagnosisDiagnosisApexController 
{
    
    @AuraEnabled
    public static List<DiagnosisListItemWrapper> getWrapperObject(List<Double> likely, List<String> diagName)
    {
        List<DiagnosisListItemWrapper> returnList = new List<DiagnosisListItemWrapper>();
        System.debug(likely);
        System.debug(diagName);
        
        for(Integer i = 0; i < likely.size(); i++)
        {
            
            
            DiagnosisListItemWrapper returnItem = new DiagnosisListItemWrapper();
            returnItem.diagJuncObj = new Diagnosis_Search_Junc__c(Likelihood__c = likely[i], Chosen__c = false);
            returnItem.diagObj = new Diagnosis__c(Name = diagName[i]);
            
            returnList.add(returnItem);
        }
        
        
        
        return returnList;
    }
    
    /*
    public class DiagnosisListItemWrapper 
    {
        @AuraEnabled public Diagnosis_Search_Junc__c diagJuncObj {get; set;}
        @AuraEnabled public Diagnosis__c diagObj {get; set;}
        
        public DiagnosisListItemWrapper()
        {
            
        }
        
        public DiagnosisListItemWrapper(Diagnosis_Search_Junc__c diagJuncObj, Diagnosis__c diagObj)
        {
            this.diagJuncObj = diagJuncObj;
            this.diagObj = diagObj;
        }
    }
*/
}