Project_3/src/objects/Diagnosis_Search_Junc__c.object
<CustomObject>
    <fields>
        <fullName>Chosen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Chosen</label>
        <type>Checkbox</type>
    </fields>
    <label>Diagnosis-Search-Junc</label>
    <nameField>
        <displayFormat>DSJ-{0}</displayFormat>
        <label>Diagnosis-Search-Junc Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diagnosis-Search-Juncs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project_3/src/classes/DiagnosisDiagnosisItemApexController.cls
public class DiagnosisDiagnosisItemApexController 
{
	@AuraEnabled
    public static Boolean setToChosen(Diagnosis_Search_Junc__c myJuncObj)
    {
		myJuncObj.Chosen__c = true;
        System.debug(myJuncObj.Chosen__c);
        try
        {
            update myJuncObj;
        }
        catch(DMLException e)
        {
            //return false;
            throw e;
        }
        return true;
    }
}