Project_3/src/objects/Diagnosis__c.object
<CustomObject>
    <label>Diagnosis</label>
    <nameField>
        <label>Diagnosis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diagnosis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project_3/src/objects/Diagnosis_Search_Junc__c.object
<CustomObject>
    <fields>
        <fullName>Diagnosis__c</fullName>
        <label>Diagnosis</label>
        <referenceTo>Diagnosis__c</referenceTo>
        <relationshipLabel>Diagnosis-Search-Juncs</relationshipLabel>
        <relationshipName>Diagnosis_Search_Juncs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Diagnosis-Search-Junc</label>
    <nameField>
        <displayFormat>DSJ-{0}</displayFormat>
        <label>Diagnosis-Search-Junc Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diagnosis-Search-Juncs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project_3/src/objects/Remedy__c.object
<CustomObject>
    <fields>
        <fullName>Diagnosis__c</fullName>
        <label>Diagnosis</label>
        <referenceTo>Diagnosis__c</referenceTo>
        <relationshipLabel>Remedies</relationshipLabel>
        <relationshipName>Remedies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Remedy</label>
    <nameField>
        <label>Remedy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remedies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project_3/src/classes/DiagnosisListItemWrapper.cls
public class DiagnosisListItemWrapper 
{
    @AuraEnabled public Diagnosis_Search_Junc__c diagJuncObj {get; set;}
    @AuraEnabled public Diagnosis__c diagObj {get; set;}
    @AuraEnabled public List<Remedy__c> remedyList {get; set;}
    
    public DiagnosisListItemWrapper()
    {
        
    }
    
    public DiagnosisListItemWrapper(Diagnosis_Search_Junc__c diagJuncObj, Diagnosis__c diagObj)
    {
        this.diagJuncObj = diagJuncObj;
        this.diagObj = diagObj;
    }
}