Project_3/src/objects/Search__c.object
<CustomObject>
    <label>Search</label>
    <nameField>
        <displayFormat>SN-{0}</displayFormat>
        <label>Search Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Searches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project_3/src/objects/Symptom__c.object
<CustomObject>
    <label>Symptom</label>
    <nameField>
        <label>Symptom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Symptoms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project_3/src/objects/Symptom_Search_Junc__c.object
<CustomObject>
    <fields>
        <fullName>Search__c</fullName>
        <label>Search</label>
        <referenceTo>Search__c</referenceTo>
        <relationshipLabel>Symptom-Search-Juncs</relationshipLabel>
        <relationshipName>Symptom_Search_Juncs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Symptom__c</fullName>
        <label>Symptom</label>
        <referenceTo>Symptom__c</referenceTo>
        <relationshipLabel>Symptom-Search-Juncs</relationshipLabel>
        <relationshipName>Symptom_Search_Juncs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Symptom-Search-Junc</label>
    <nameField>
        <displayFormat>SSJ-{0}</displayFormat>
        <label>Symptom-Search-Junc Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Symptom-Search-Juncs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project_3/src/classes/DiagnosisSymptomsApexController.cls
/**
 * Creator: Larry Resnik
 * Created: 1/16/2019
 * Changed: 1/16/2019
 * Apex controller that gets human-readable symptoms related to some search.
 */
public class DiagnosisSymptomsApexController {
    /**
     * Gets the names of all symptoms related to some search.
     * @author	Larry Resnik
     * @param	searchId	The search junction object's unique identifier.
     * 			It should have a format like SN-####.
     * @return	A list of human-readable symptoms.
     * @since	1.0
     */
	@AuraEnabled
    public static List<String> getSymptomNamesFromSearch(String searchId) {
        List<String> symptomNames = new List<String>();
        for (Symptom_Search_Junc__c searchObj :
             [SELECT Id, Search__c, Symptom__c, Symptom__r.Name
              FROM Symptom_Search_Junc__c
              WHERE Search__r.Name = :searchID]) {
            symptomNames.add(searchObj.Symptom__r.Name);
        }
        return symptomNames;
    }
}